config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get "/github/setup", to: "github/setup#update"
  namespace :github do
    resources :repos, only: [:index, :create]
  end

  root 'posts#index'
  get 'posts/my_posts', to: 'posts#my_posts'
  resources :posts, only: %i[new create edit update show destroy] do
    member do
      patch :solve
      patch :sync_to_github
    end
    resources :comments, only: %i[create destroy]
  end

  resources :comments, only: [] do
    collection do
      get :new_reply
    end
    member do
      patch :set_best_comment
    end
  end

  get 'tags/search', to: 'tags#search'
  get "/help", to: "guides#help", as: :help

  # API関連
  post '/api/upload-image', to: 'images#upload'
  delete "/api/images/:id", to: "images#destroy"
end

app/views/shared/_form.html.erb
<% unattached_blobs_json = (@unattached_blobs || []).to_json %>

<div class="container mx-auto px-4 py-8 max-w-7xl">
  <%= form_with model: @post, local: true,
    data: {
      controller: "markdown-editor",
      "markdown-editor-unattached-blobs-value": unattached_blobs_json,
      "markdown-editor-images-allowed-value": true,
    }, class: "post-editor" do |f| %>
    <div class="mb-6">
      <label for="post_title" class="block text-sm font-medium text-terminal-text mb-2" >
        タイトル
      </label>
      <%= f.text_field :title, class: "w-full px-3 py-2 border border-terminal-border bg-terminal-input text-terminal-text rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-terminal-accent/50 focus:border-terminal-accent" %>
    </div>

    <div class="mb-6" data-controller="tag-manager">
      <%= f.label :tag_names, "タグ (カンマ区切り)", class: "block text-sm font-medium text-terminal-text mb-2" %>
      <%= f.text_field :tag_names,
          class: "w-full px-3 py-2 border border-terminal-border bg-terminal-input text-terminal-text rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-terminal-accent/50 focus:border-terminal-accent",
          value: @post.tags.map(&:name).join(', ') %>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6 min-h-[500px]">
      <%# エディタ側 %>
      <div class="flex flex-col h-full">
        <label for="markdown-editor" class="block text-sm font-medium text-terminal-text mb-2">
          内容（Markdown形式）
        </label>
        <div class="relative flex-grow">
          <%= f.text_area :content,
              id: "markdown-editor",
              class: "w-full h-full bg-terminal-input border border-terminal-border text-terminal-text rounded-lg",
              data: { "markdown-editor-target": "editor" } %>
        </div>
      </div>

      <%# プレビュー側 %>
      <div class="flex flex-col h-full">
        <label class="block text-sm font-medium text-terminal-text mb-2">
          プレビュー
        </label>
        <div id="preview-container"
            class="prose prose-invert max-w-none
                  border border-terminal-border rounded-lg
                bg-terminal-input p-6 shadow-sm
                prose-headings:text-terminal-text
                prose-a:text-terminal-accent
                prose-p: text-terminal-text
                prose-pre:bg-terminal-input
                prose-pre:text-terminal-text
                prose-code:text-terminal-text"
            data-markdown-editor-target="preview">
          <p class="text-gray-400 italic not-prose">ここに内容のプレビューが表示されます</p>
        </div>
      </div>
    </div>

    <% if @unattached_blobs %>
      <% @unattached_blobs.each do |blob| %>
        <input type="hidden" name="post[images][]" value="<%= blob[:signed_id] %>">
      <% end %>
    <% end %>

    <div class="flex justify-end space-x-4 mt-8">
      <button type="button"
              class="px-4 py-2 font-medium bg-terminal-accent text-terminal-bg rounded-lg hover:bg-terminal-accent/80 transition-colors duration-200"
              data-action="click->markdown-editor#insertTemplate">
        テンプレートを挿入
      </button>
      <%= f.submit "保存", class: "px-6 py-2 bg-terminal-accent text-terminal-bg font-medium rounded-lg hover:bg-terminal-accent/80 focus:outline-none focus:ring-2 focus:ring-terminal-accent/50 focus:ring-offset-2 transition-colors duration-200" %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<header class="bg-terminal-bg text-terminal-text body-font border-b-2 border-terminal-border">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center" data-controller="navbar">
    <a href="/" class="flex title-font font-medium items-center text-terminal-text mb-4 md:mb-0">
      <%= render 'shared/logo_svg' %>
      <span class="text-xl">Wakannyai</span>
    </a>

    <button id="hamburger-button" data-action="click->navbar#toggleMenu" class="md:hidden absolute top-4 right-4 active text-terminal-text">
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
    </button>

    <nav class="hidden w-full space-x-5 md:flex md:w-auto md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-terminal-border flex-wrap items-center text-base justify-center">
      <%= link_to "新規作成", new_post_path, class:"hover:text-terminal-accent transition-all duration-300" %>
      <%= link_to "あなたのQ&A", posts_my_posts_path, class:"hover:text-terminal-accent transition-all duration-300" %>
      <%= link_to "使い方", help_path, class: "hover:text-terminal-accent transition-all duration-300" %>
    </nav>

    <%= button_to(current_user ? destroy_user_session_path : new_user_session_path,
            class: "inline-flex items-center bg-terminal-accent text-terminal-bg border-0 py-1 px-3 focus:outline-none cursor-pointer rounded-lg text-base mt-4 md:mt-0 hover:bg-terminal-text",
            form: { class: "hidden md:flex" },
            method: current_user ? :delete : :get) do %>
      <%= current_user ? 'ログアウト' : 'ログイン' %>
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    <% end %>

    <div id="nav-menu" data-navbar-target="menu" class="hidden fixed inset-0  bg-opacity-50 z-50 transition-transform transform translate-x-full">
      <div class="bg-terminal-bg w-2/3 h-full absolute right-0 p-8 flex flex-col items-start">
        <button id="hamburger-button" data-action="click->navbar#toggleMenu" class="absolute top-4 right-4 active text-terminal-text">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6L18 18"></path>
          </svg>
        </button>
        <div class="w-full mb-4">
          <a href="/" class="block py-2 text-terminal-text">Home</a>
          <% if current_user %>
            <%= link_to "新規作成", new_post_path, class:"block py-2 text-terminal-text" %>
            <%= link_to "あなたのQ&A", posts_my_posts_path, class:"block py-2 text-terminal-text" %>
            <%= link_to "ログアウト", destroy_user_session_path, class:"block py-2 text-terminal-text", data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class:"block py-2 text-terminal-text" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_logo_svg.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000" viewBox="0 0 1000 1000" class="h-18 w-18 logo-fill">
  <path d="M 465 248 L 476 355 L 343 306 L 344 342 L 361 402 L 312 446 L 283 554 L 239 574 L 231 587 L 234 626 L 251 648 L 252 632 L 262 633 L 276 651 L 283 636 L 312 662 L 324 698 L 323 714 L 310 712 L 315 731 L 372 750 L 480 751 L 585 724 L 660 671 L 694 599 L 695 544 L 683 490 L 639 421 L 611 354 L 552 293 Z" />
</svg>

app/views/shared/_search_form.html.erb
<%= search_form_for @q, class: "flex w-full justify-center items-end", url: root_path do |f| %>
  <div class="relative mr-4 lg:w-full xl:w-1/2 w-2/4 md:w-full text-left">
    <%= f.label :title_or_content_or_tags_name_cont, "タイトルやタグ、本文からみんなの学習記録を検索できます。",
                class: "leading-7 text-sm text-terminal-text" %>
    <%= f.search_field :title_or_content_or_tags_name_cont, 
                       class: "w-full bg-terminal-input bg-opacity-50 rounded focus:ring-2 focus:ring-terminal-accent/50 focus:bg-transparent border border-terminal-border focus:border-terminal-accent text-base outline-none text-terminal-text py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
  </div>
  <%= f.submit "検索", class: "inline-flex text-base bg-terminal-accent text-terminal-bg font-bold border-0 py-2 px-6 focus:outline-none cursor-pointer rounded text-lg" %>
<% end %>